export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const FETCH_SERVCATAGORIES = "FETCH_SERVCATAGORIES";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const FETCH_ITEMS = "FETCH_ITEMS";
export const LOAD_STATUS = "LOAD_STATUS";

export const UPDATE_LISTINGS = "UPDATE_LISTINGS";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_WEEKLYVENDORS = "FETCH_WEEKLYVENDORS";
export const FETCH_BUSINESSADVERTISEMENT = "FETCH_BUSINESSADVERTISEMENT";
export const AUTH_USER="AUTH_USER"
export const SHOW_NOTIFICATION="SHOW_NOTIFICATION"
export const CLEAR_MSG="CLEAR_MSG"
export const IS_LOGOUT="IS_LOGOUT"

  